export const INIT_SERVICES = 'service/INIT_SERVICES' as const;
export const GET_SERVICES_BY_CATEGORYIDX =
  'service/GET_SERVICES_BY_CATEGORYIDX' as const;
export const GET_SERVICES_BY_CATEGORYIDX_SUCCESS =
  'service/GET_SERVICES_BY_CATEGORYIDX_SUCCESS' as const;
export const GET_SERVICES_BY_CATEGORYIDX_ERROR =
  'service/GET_SERVICES_BY_CATEGORYIDX_ERROR' as const;

export const GET_TOTAL_SERVICE_COUNT =
  'service/GET_TOTAL_SERVICE_COUNT' as const;
export const GET_TOTAL_SERVICE_COUNT_SUCCESS =
  'service/GET_TOTAL_SERVICE_COUNT_SUCCESS' as const;
export const GET_TOTAL_SERVICE_COUNT_ERROR =
  'service/GET_TOTAL_SERVICE_COUNT_ERROR' as const;
